version: "3"
services:
  web:
    build:
        context: .
    image: registry.cn-hangzhou.aliyuncs.com/ringtail/lucas:0.0.2
    environment:
      - CA_FILE=""
      - KEY_FILE=""
      - CERT_FILE=""
      - ENDPOINTS=""
    ports:
      - 8080:8080
